### ISSUE TITLE
Problem z uzyskaniem wyniku

### ISSUE THREAD

**Issue by wink05** [iwo-strzebonski/RevasBot#14]
Cześć! Próbuję u siebie postawić RevasBota i wszystko działa, dopóki nie próbuje pobrać wyników. Pojawia się error:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\winko\Desktop\RevasBot-main\main.py", line 21, in <module>
    revasbot.setup()
  File "C:\Users\winko\Desktop\RevasBot-main\revasbot\__init__.py", line 105, in setup
    revas_scrapper.scrap_scores()
  File "C:\Users\winko\Desktop\RevasBot-main\revasbot\selenium\revas_scrapper.py", line 135, in scrap_scores
    scores = self.revas_selenium.get_scores()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\winko\Desktop\RevasBot-main\revasbot\selenium\revas_selenium.py", line 153, in get_scores
    data = [
           ^
  File "C:\Users\winko\Desktop\RevasBot-main\revasbot\selenium\revas_selenium.py", line 154, in <listcomp>
    {
  File "C:\Users\winko\Desktop\RevasBot-main\revasbot\selenium\revas_selenium.py", line 157, in <dictcomp>
    )[0].text: int(row.find_elements(
               ^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''
```

Pojawia się on na /ajax.php?mod=sale&tab=results

Jakieś znane rozwiązanie tego problemu? :D

**Comment by iwo-strzebonski** [comment]
z jakiej przeglądarki korzystasz?

**Comment by wink05** [comment]
> z jakiej przeglądarki korzystasz?

Edge 112.0.1722.48 + EdgeDriver 112.0.1722.39

**Comment by iwo-strzebonski** [comment]
nie wiem, czy będę mógł cokolwiek zrobić, jako że od dawna nie mam dostępu do żadnej aktywnej rozgrywki

**Comment by wink05** [comment]
> nie wiem, czy będę mógł cokolwiek zrobić, jako że od dawna nie mam dostępu do żadnej aktywnej rozgrywki

jeśli jesteś w stanie coś spojrzeć, ewentualnie naprawić to mogę podesłać na przykład kod z tej strony czy coś, daj znać!

**Comment by iwo-strzebonski** [comment]
możesz podesłać kod tej strony, oczywiście prościej by było, gdybym miał dostęp do rozgrywki

**Comment by wink05** [comment]
> możesz podesłać kod tej strony, oczywiście prościej by było, gdybym miał dostęp do rozgrywki

podesłać tutaj w odpowiedzi czy gdzieś indziej (np discord)?

**Comment by iwo-strzebonski** [comment]
@wink05 sprawdź teraz

**Comment by wink05** [comment]
> @wink05 sprawdź teraz

wybacz pozna odpowiedz, teraz problem jest taki:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\winko\Desktop\RevasBot-main\main.py", line 21, in <module>
    revasbot.setup()
  File "C:\Users\winko\Desktop\RevasBot-main\revasbot\__init__.py", line 105, in setup
    revas_scrapper.scrap_scores()
  File "C:\Users\winko\Desktop\RevasBot-main\revasbot\selenium\revas_scrapper.py", line 135, in scrap_scores
    scores = self.revas_selenium.get_scores()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\winko\Desktop\RevasBot-main\revasbot\selenium\revas_selenium.py", line 153, in get_scores
    data = [
           ^
  File "C:\Users\winko\Desktop\RevasBot-main\revasbot\selenium\revas_selenium.py", line 154, in <listcomp>
    {
  File "C:\Users\winko\Desktop\RevasBot-main\revasbot\selenium\revas_selenium.py", line 158, in <dictcomp>
    float(
ValueError: could not convert string to float: ''
```

**Comment by iwo-strzebonski** [comment]
@wink05 sprawdź teraz

**Comment by wink05** [comment]
> @wink05 sprawdź teraz

Dobra, wygląda na to że udało się to naprawić :)
Aczkolwiek, niestety teraz wyskakuje inny problem, niby wyglądało łatwo ale nie jestem w stanie sobie poradzić...
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\winko\Desktop\RevasBot-main\main.py", line 21, in <module>
    revasbot.setup()
  File "C:\Users\winko\Desktop\RevasBot-main\revasbot\__init__.py", line 105, in setup
    revas_scrapper.scrap_scores()
  File "C:\Users\winko\Desktop\RevasBot-main\revasbot\selenium\revas_scrapper.py", line 136, in scrap_scores
    RevasPandas.dict_to_xlsx(
  File "C:\Users\winko\Desktop\RevasBot-main\revasbot\revas_pandas.py", line 19, in dict_to_xlsx
    writer.save()
    ^^^^^^^^^^^
AttributeError: 'OpenpyxlWriter' object has no attribute 'save'. Did you mean: '_save'?
```

**Comment by iwo-strzebonski** [comment]
@wink05 a w jaki sposób zainstalowałeś projekt i potrzebne moduły?

**Comment by wink05** [comment]
> @wink05 a w jaki sposób zainstalowałeś projekt i potrzebne moduły?

właśnie przeinstalowałem jeszcze raz wszystko na czysto (używając miniconda), zainstalowałem, doinstalowałem pandas bo sie wywalało, potem na tym etapie wywalało że nie ma openpyxl to zrobiłem po prostu `pip install openpyxl` i niestety dzieje sie to samo co wyżej

**Comment by iwo-strzebonski** [comment]
@wink05 to w takim razie usuń wszystko, zreinstaluj Condę, dodaj conda-forge do kanałów i utwórz środowisko na podstawie pliku environment.yml
